### ISSUE TITLE
Please provide steps for how to build wsclient-plus-plus

### ISSUE THREAD

**Issue by shahasachin** [neurospeech/wsclient-plus-plus#1]
I am new to Air Sdk, but don't know how to open and build. 
Can you please provide steps?

Thanks and Regards,
Sachin Shaha

**Comment by ackava** [comment]
If you want to build WSClientForJava then you have to open folder `MAIN/Code/WSClientForJava` in the Adobe AIR Studio, and then you have to hit the Run.
